
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "@/components/appWraper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='font-sans'>
        <div className="bg-[#FFFDD0] h-screen">
          <AppWrapper>
            {children}
          </AppWrapper>
        </div>
      </body >
    </html >
  );
}
